name: general

on: push

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: setup project
        run: make setup

      - name: start tests
        run: make test

      - name: start linter
        run: make lint

      - name: hello Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
